# config.yaml
query:
  body: |
    query GetIssues($cursor: String) {
      repository(owner: "pytorch", name: "pytorch") {
        issues(first: 100, after: $cursor) {
          totalCount
          nodes {
            number 
            title
            body
            createdAt
            state
            labels(first: 100) { nodes { name } }
            reactions { totalCount }
            comments { totalCount }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }


model:
  model_path: "Qwen/Qwen2.5-Coder-7B-Instruct"
  temperature: 1
  top_p: 0.8
  repetition_penalty: 1.05
  max_tokens: 128
  system_content: "Your are an excellent issue summarizer."
  prompt_template: "Here is the issue title: {title}. \nHere is the issue body: {body}. \nHere is the issue code: {code}. \nNote that issue body or code may be nan (means empty). Please help me analyze this issue from memory aspect. Give me the issue symptom and solution."
