# config.yaml
query:
  includeFields:
    number: true
    title: true
    body: true
    createdAt: true
    state: true
    labels: true
    reactions: true
    comments: true
  body: |
    query GetIssues($cursor: String) {
      repository(owner: "pytorch", name: "pytorch") {
        issues(first: 100, after: $cursor) {
          totalCount
          nodes {
            number 
            title
            body
            createdAt
            state
            labels(first: 100) { nodes { name } }
            reactions { totalCount }
            comments { totalCount }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
