# config.yaml
query:
  issue_query: |
    query GetIssues($cursor: String, $owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        issues(first: 100, after: $cursor) {
          totalCount
          nodes {
            number 
            title
            body
            createdAt
            state
            labels(first: 100) { nodes { name } }
            reactions { totalCount }
            comments { totalCount }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
  pr_query: |
    query GetPullRequests($cursor: String, $owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        pullRequests(first: 100, after: $cursor) {
          totalCount
          nodes {
            number 
            title
            body
            createdAt
            state
            # PR-specific filed starts #
            merged
            mergedAt
            baseRefName
            headRefName
            isDraft
            # PR-specific filed ends #
            labels(first: 100) { nodes { name } }
            reactions { totalCount }
            comments { totalCount }
            # optional review information #
            reviews(first: 1) { totalCount }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }

model:
  model_path: "Qwen/Qwen3-MoE-15B-A2B"
  temperature: 1
  top_p: 0.8
  repetition_penalty: 1.05
  max_tokens: 128
  system_content: "Your are an excellent issue summarizer."
  prompt_template: | 
    Here is the issue title: {title}. 
    Here is the issue body: {body}. 
    Here is the issue code: {code}. 
    Note that issue body or code may be nan (means empty). Please help me analyze this issue from memory aspect. 
    Give me the issue symptom and solution.